In [29]:
import pandas as pd

In [37]:
df_match = pd.read_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/all_matches.csv')

In [38]:
# removed extra index column
df_match.drop(df_match.columns[0], axis = 1, inplace = True)

**Handling batting summary**

In [75]:
df_batting = pd.read_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/batting_summary.csv')

In [76]:
# removed extra index column
df_batting.drop(df_batting.columns[0], axis = 1, inplace = True)
df_batting

,match,team,batting_Pos,batsman,out/not out,run,ball,m,fours,sixes,strike_rate
0,Pakistan Vs England,Pakistan,1,Mohammad Rizwan †,b Curran,15,14,24,0,1,107.14
1,Pakistan Vs England,Pakistan,2,Babar Azam (c),c & b Rashid,32,28,58,2,0,114.28
2,Pakistan Vs England,Pakistan,3,Mohammad Haris,c Stokes b Rashid,8,12,15,1,0,66.66
3,Pakistan Vs England,Pakistan,4,Shan Masood,c Livingstone b Curran,38,28,46,2,1,135.71
4,Pakistan Vs England,Pakistan,5,Iftikhar Ahmed,c †Buttler b Stokes,0,6,8,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
694,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga,c Loftie-Eaton b Scholtz,4,8,9,0,0,50.00
695,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,15,0,0,62.50
696,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,run out (van Lingen/†Green),0,0,4,0,0,-
697,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,20,0,0,53.33
698,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,not out,11,11,14,0,1,100.00

In [52]:
# df_batting.rename(columns = {'out/not out':'dismissal'}, inplace = True)

In [54]:
# df_batting['out/ not out'] = df_batting.dismissal.apply(lambda x: "out" if len(x) > 0 else "not out")

In [77]:
# replacing extra text with out in out/not out column
df_batting['out/not out'] = df_batting['out/not out'].apply(lambda x: "out" if x != "not out" else x )

In [91]:
# stroing scorecard/match_id in a dictionary so that i can connect each 
# table with this uniqu match id
match_id_dict = {}

for index, row in df_match.iterrows():
    key1 = row['Team 1'] + ' Vs ' + row['Team 2']
    key2 = row['Team 2'] + ' Vs ' + row['Team 1']
    match_id_dict[key1] = row['Scorecard']
    match_id_dict[key2] = row['Scorecard']

In [92]:
# creating new column named match_id and filling values according to match with keys of match_id_dict
df_batting['match_id'] = df_batting['match'].map(match_id_dict)

**change scorecard to match**

In [95]:
# renaming the scoredcard to match_id as it is confusing
df_match.rename(columns = {'Scorecard':'match_id'}, inplace = True)

**Handling bolling summary**

In [97]:
# now connected match_id with bolling summary
df_bolling = pd.read_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/balling_summary.csv')

In [103]:
df_bolling.drop(df_bolling.columns[0], axis = 1, inplace = True)

In [105]:
df_bolling['match_id'] = df_bolling['match'].map(match_id_dict)

In [106]:
df_bolling

,match,bowlingTeam,bowler,overs,maiden,runs,wicktes,economy,zeros,fours,sixex,wides,noBalls,match_id
0,Pakistan Vs England,Pakistan,Ben Stokes,4.0,0,32,1,8.00,6,1,0,2,1,T20I # 1879
1,Pakistan Vs England,Pakistan,Chris Woakes,3.0,0,26,0,8.66,7,2,1,2,0,T20I # 1879
2,Pakistan Vs England,Pakistan,Sam Curran,4.0,0,12,3,3.00,15,0,0,0,0,T20I # 1879
3,Pakistan Vs England,Pakistan,Adil Rashid,4.0,1,22,2,5.50,10,1,0,1,0,T20I # 1879
4,Pakistan Vs England,Pakistan,Chris Jordan,4.0,0,27,2,6.75,9,3,0,0,0,T20I # 1879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Namibia Vs Sri Lanka,Sri Lanka,David Wiese,4.0,0,16,2,4.00,13,1,0,0,0,T20I # 1823
496,Namibia Vs Sri Lanka,Sri Lanka,Bernard Scholtz,4.0,0,18,2,4.50,10,1,0,0,0,T20I # 1823
497,Namibia Vs Sri Lanka,Sri Lanka,Ben Shikongo,3.0,1,22,2,7.33,6,3,0,0,0,T20I # 1823
498,Namibia Vs Sri Lanka,Sri Lanka,JJ Smit,3.0,0,16,1,5.33,7,0,0,1,0,T20I # 1823
499,Namibia Vs Sri Lanka,Sri Lanka,Jan Frylinck,4.0,0,26,2,6.50,10,0,2,1,0,T20I # 1823

**Handling Players profile**

In [108]:

df_profile = pd.read_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/player_profiles.csv')

In [110]:
df_profile.drop(df_profile.columns[0], axis = 1, inplace = True)

In [112]:
df_profile.to_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/players_profile.csv')

In [116]:
df_match.to_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/matches.csv')

In [117]:
df_bolling.to_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/bowling.csv')

In [118]:
df_batting.to_csv(r'C:\Users\praja\Downloads\shooting-range-master\Projects\T20_2022_players_analysis\data cleaning & transformation/batting.csv')